import "./globals.css";
import { Approvider } from "./contextapi";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Approvider>{children}</Approvider>
      </body>
    </html>
  );
}
